(use-modules (ice-9 ftw))

(define (run-test filename statinfo flag)
  (cond ((== flag 'regular)
         ;(display* "Checking " filename "\n")
         (when (string-ends? filename ".tm")
           (display* "Converting " filename "... ")
           (with new-name (string-append filename ".md")
             (file-convert filename new-name)
             (files-equal? filename new-name)))
         #t)
        ((== flag 'directory)
         (display* "Entering directory: " filename "\n")
           #t)
        (else #f)))

(define (files-equal? a b)
  (if (== 0 (system (string-append "diff -q \"" a "\" \"" b "\"")))
      (display "OK.")
      (display "ERROR.")))

; FIXME: make test config local to the tests (e.g. with local preferences.scm)
(with save-hugo (get-preference "texmacs->markdown:hugo-extensions")
  (with save-width (get-preference "texmacs->markdown:paragraph-width")
    (set-preference "texmacs->markdown:hugo-extensions" "off")
    (set-preference "texmacs->markdown:paragraph-width" 79)
    (ftw "./vanilla/" run-test)
    (set-preference "texmacs->markdown:hugo-extensions" "on")
    (set-preference "texmacs->markdown:paragraph-width" #f)
    (ftw "./hugo/" run-test)
    (set-preference "texmacs->markdown:hugo-extensions" save-hugo)
    (set-preference "texmacs->markdown:paragraph-width" save-width)))


